[server]
# Path to SteamCMD installation directory:
# steamcmd_dir = "C:/steamcmd"    # Absolute path example
steamcmd_dir = "./steamcmd"       # Relative path example
username = "username"             # Steam account name (login once manually to cache credentials)

[mods]
# Server-side mods (run on server only, clients don't need to download)
# server_mod_list = [
# Format: { id = WorkshopID, name = "Mod Name" }
# ]

# Steam Workshop collection for client mods
# mod_collection_url = "https://steamcommunity.com/sharedfiles/filedetails/?id=3489459461"
