[server]
steamcmd_dir = "C:/SteamCMD"      # Path to SteamCMD executable
server_app_id = 223350            # App ID for DayZ Dedicated Server
game_app_id = 221100              # App ID for DayZ (base game)
username = "username"             # Steam account name (login once manually to cache credentials)

[mods]
mod_list = [
    # Format: { id = WorkshopID, name = "Mod Name" }
    # Example (uncomment to use):
    # { id = 1582756848, name = "ZomBerry Admin Tools" },
]